### PR TITLE
Pass hashed URL to Wallabag when testing for entry existence, rather than cleartext URL

### PR DESCRIPTION
**Pull request by 00dani**
This addresses issue #204, which I opened myself quite some time ago. The general implementation is fairly simple, but because Wallabagger officially supports Edge > 14 there were some polyfills required for compatibility - if we're happy to only support the Chromium-based versions of Edge first introduced in 2019 with Edge 79, then all of these polyfills can be safely removed.

The Wallabag server version is taken into account, and Wallabagger will automatically fall back to using cleartext URLs if it's talking to an older server that doesn't support `hashed_url`. Most should at this point, though, since 2.4.0 was released almost three years ago (!!).

### CODE REVIEW

**Comment by lsferreira42** [comment]
Hello,

How can i help this pull request? It's a very wanted feature as i use a shared wallabag instance with some friends and this is a privacy concern!

**Comment by 00dani** [comment]
@lsferreira42 Well, the PR ought to be ready to merge, now that I've fixed up that conflict in package-lock.json. Depending on our targeted browsers, it might make sense to remove the polyfills I included for cryptography, but they're not gonna actually hurt anything if they are included.

The problem is that it looks like Wallabagger isn't very actively maintained, since I put this up back in October and it doesn't seem like any maintainers have looked at it since then. 🤔

**Comment by Simounet** [comment]
I'm really sorry for this delay. I'll look into it this week.

**Comment by lsferreira42** [comment]
Thank you @Simounet !!

**Comment by Simounet** [comment]
Thank you so much @00dani for this feature! And I'm really sorry for the delay… I'll push it into a new release ASAP.

**Pull request merged**
