### PR TITLE
Green icon if page saved

### PR DESCRIPTION
**Pull request by Rurik19**

### CODE REVIEW

**Comment by nicosomb** [comment]
😍 👍

**Comment by tcitworld** [comment]
Maybe add a information section to warn that this option will send all of your browsing history from now on to the wallabag server, and maybe enforce https for this option ?

**Comment by nicosomb** [comment]
+1 with @tcitworld. 
Maybe we can a setting to enable this feature.

**Comment by Rurik19** [comment]
Yeah, I agree, option to enable | disable will be done tomorrow.
@tcitworld what do you mean "enforce https" = if wallabag is set up on http then https request fails, and if it set up https request IS already https

**Comment by tcitworld** [comment]
I mean that for this option to be activable, the url should be set to https first, because sending all of my history through clear traffic on my network (though it concerned https traffic at first) seems like a security issue.
It's 2017, we should require https for everything regarding personal informations.

**Comment by Rurik19** [comment]
Here it is:

image

image

**Comment by Rurik19** [comment]
Hi all! Can somebody tell me about the rule of adding final / while saving page to wallabag? What I understand:
- if there is an extension (as .html) - no slash
- if there are parameters ( after ? ) - no slash
but in other cases (url ends by just a word) I cannon catch the rule:
-- for  https://habrahabr.ru/post/319558 wallabag adds slash but http://worldcrisis.ru/crisis/1935630 - don't

**Comment by Rurik19** [comment]
Meanwhile.... Why we cannot guess final url? Yes we CAN. If preliminary OPTIONS request to the url returns 301 or 302 then location field in headers = next URL to check. That which retutns 200 will be the final. I've checked, that works even to bit.ly type shorteners. But I think it should be made in api/exists function as well as in api/entries and in adding in interface. I'll make an issue in wallabag project

**Comment by Simounet** [comment]
There is too many possibilities. The only valid solution is for the site to handle a canonical URL that we can use as a known main content. I will try the code later today for further validation.

**Pull request merged**
