### PR TITLE
Reduce permissions

### LINKED ISSUE #194: Explain permissions change
Previously, it seems Wallabagger (Firefox) only required info about browser tabs. Now it can "Access your data for all websites" which is scary. Can you explain why this change was made and why it's necessary?

### PR DESCRIPTION
**Pull request by Simounet**
Fix #194 .
@Rurik19  @AKKED @jacobkiers @88431844, could you update your translation files and do a PR on this `feat/reduce-permissions` branch please?

### CODE REVIEW

**Comment by Simounet** [comment]
@Strubbl we could need your help here please. :de:

**Comment by Strubbl** [comment]
is there some tool support available for the translation? or is it just plain text editing?

**Comment by Simounet** [comment]
I'm sorry but there is no tool for translation right now. You can translate it here and we will integrate that ourselves.
- Agreed
- Denied
- Wallabag permission checked
- We need an access to your wallabag instance to read, write and update content. Please, test the URL again and accept the request.

**Comment by Strubbl** [comment]
I am going to file a PR tonight.

**Comment by Simounet** [comment]
Thanks!

**Pull request merged**
