### PR TITLE
Fix #54 User option for debugging purpose added

### LINKED ISSUE #54: Debug handling
We have to remove these `console.log` always on for debugging purpose or handle it differently. I will add an option to enable/disable these messages.
A plus would be to auto disable the debug logging on browser restart.

### PR DESCRIPTION
**Pull request by Simounet**
Add an option into the option page the user can toggle to enable/disable the debug lines.
The option is toggle off on browser restart to be sure it is not kept on.

### CODE REVIEW

**Comment by Rurik19** [comment]
All of this seems slightly overwhelmed. Why just not remove console.log?

**Comment by Rurik19** [comment]
and I should make too many changes in the background-api branch - there will be no api in popup and options.

**Comment by Simounet** [comment]
Because it is useful for debugging purpose. How can we help people without any information?

**Comment by Simounet** [comment]
:/

**Comment by Rurik19** [comment]
1) Ok, if we have debug option, let's collect more useful info = all request and responses would be great
2) how user send us this debug info - saving to file or send by email would be great

**Comment by Rurik19** [comment]
ok, all that is the future :)

**Pull request merged**
