### PR TITLE
changed icons to not look like a pair of saggy tits

### PR DESCRIPTION
**Pull request by thgie**

### CODE REVIEW

**Comment by j0k3r** [comment]
Screenshots?

**Comment by Simounet** [comment]
I'm sorry but I don't get why you want to change it.

**Comment by thgie** [comment]
I believe it makes sense to have the same visual language as the wallabag plattform itself. The dots make not much sense and could be seen as some kind of weird indicator.

**Comment by Rurik19** [comment]
The man has a good imagination :smile: . The icon won't be changed.

**Comment by thgie** [comment]
I tried. Thanks for the conversation and the good work 💪🏻

**Pull request closed without merging**
