### PR TITLE
Hotkey for background saving, works in FF-stable

### PR DESCRIPTION
**Pull request by Rurik19**
For #13, instead of #21

### CODE REVIEW

**Comment by Simounet** [comment]
I did some changes. We have to use `browser` instead of `chrome` for a better compatibility.
The Alt key is a modifier and must be the first https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Key_combinations.

**Comment by Rurik19** [comment]
Ok, that's fine, tested it again in chrome.

**Comment by falematte** [comment]
Which one is the correct hotkey?

**Comment by Simounet** [comment]
Should be `ALT` + `SHIFT` + `W`.

**Comment by falematte** [comment]
Thank you!

**Pull request merged**
