### PR TITLE
Fetch api separated, temporary XMLHttpRequest for Edge

### PR DESCRIPTION
**Pull request by Rurik19**

### CODE REVIEW

**Comment by Rurik19** [comment]
@Simounet it is far from working on Edge, I just begin to test and XMLrequest is easier to debug.

**Comment by Simounet** [comment]
Ok so, can we use this PR to make it work on Edge? I don't see the point of merging that with no direct benefits on the current branch.

**Comment by Rurik19** [comment]
@Simounet this PR not about Edge, it stuctures the code a little :-) I have a brand new branch about all background and caching matters and I would like to see this changes there also. You shoulg begin to see it - there tons of changes :-) https://github.com/wallabag/wallabagger/tree/background-api

**Comment by Simounet** [comment]
Ok, nice. In that case: 👍

**Pull request merged**
