### PR TITLE
Hotkey for background saving, works in FF-stable

### PR DESCRIPTION
**Pull request by Rurik19**
For https://github.com/wallabag/wallabagger/issues/13

### CODE REVIEW

**Comment by Simounet** [comment]
It is great but I don't think that Alt+A is a good idea. It won't work with every language having a word from the Firefox menu starting with an A. It is the case in french with `Affichage`. The combination of Alt+A popup the `Affichage` menu. We should propose a trickier combination or the best scenario would be to let the user choosing its shortcut with the option page. What do you think?

**Comment by Rurik19** [comment]
Which shortcut do you propose? Combinations ctrl+alt doesn't work. 
I propose Shift+Alt+W, because Alt+W is for browser action for chrome now

**Comment by Simounet** [comment]
Shift+Alt+W seems ok.

**Comment by Rurik19** [comment]
closing because of odd commits, I created #22 istead

**Pull request closed without merging**
